### ISSUE TITLE
neverbleed_load_private_key _file failed with ECDSA key pair

### ISSUE THREAD

**Issue by tatsuhiro-t** [h2o/neverbleed#10]
When I fed ECDSA key pair to neverbleed_load_private_key_file, then it returned error saying "neverbleed_load_private_key_file failed: failed to parse the private key".

Using ordinal openssl library function works fine.

I created ECDSA key pair using:

```
openssl req -new -x509 -nodes -newkey ec:<(openssl ecparam -name secp384r1) -keyout ecdsa.key -out ecdsa.crt -days 3650
```

http://security.stackexchange.com/questions/58077/generating-ecdsa-certificate-and-private-key-in-one-step

**Comment by kazuho** [comment]
Thank you for reporting the issue.

Neverbleed is implemented as an offloading engine for RSA operations.

Are you suggesting to add(or interested in adding) an ECDSA engine?  Or is your suggestion to improve the error message?

**Comment by tatsuhiro-t** [comment]
I overlooked RSA designation of neverbleed, but I think it would be great to add ECDSA support to neverbleed, since otherwise we first detect whether the given certificate is ECDSA or not to decide to use neverbleed.

**Comment by kazuho** [comment]
> I think it would be great to add ECDSA support to neverbleed

Agreed.

> therwise we first detect whether the given certificate is ECDSA or not to decide to use neverbleed.

For the meantime, I believe you can easily check if your app is going to load a RSA private key by examining the `X509*` structure of the certificate.  The code will look like:

``` c
X509 *cert = ...; // load certificate using PEM_load_X509, etc.
EVP_PKEY *pkey = X509_get_X509_PUBKEY(cert);
if (pkey != NULL && EVP_PKEY_type(pkey->type) == EVP_PKEY_RSA) {
  // the public key in the certificate is RSA
} else {
  // the public key is not RSA
}
```

**Comment by tatsuhiro-t** [comment]
Yeah, that would work for me.
I'm curious how hard to add ECDSA support to neverbleed.  I'm not familiar to OpenSSL Engine thing. So is it just changing function call or parameters?

**Comment by kazuho** [comment]
Looking at https://github.com/openssl/openssl/commits/master/crypto/ec/ec_kmeth.c, it seems like that the EC codecs have just got a engine API defined.

So I assume it would not be hard to add ECDSA support _for upcoming releases of OpenSSL_ by taking the same approach as we do for RSA; e.g. define a engine that sends the parameters over unix socket, and I think the underlying code can be shared between RSA implementaiton and the ECDSA one.

**Comment by tatsuhiro-t** [comment]
OK, so we have to wait for the development of OpenSSL.

For the record, I tried to understand neverbleed code, and then
the following is what I got:
- client process calls *_proxy function via *_METHOD, which sends command to nb daemon process.
- nb daemon reads command, and calls appropriate *_stub function.

We have already RSA_METHOD for RSA.  When new OpenSSL comes, and we
hopefully will get EC_KEY_METHOD (is that correct?), set to
ENGINE.  Then, we may add new *_proxy functions and *_stub
functions for EC_KEY.  Protocol helper functions can be shared.
We also need add new command name to call proper stub.  This can be done by adding prefix like "rsa_sign", etc.

**Comment by tatsuhiro-t** [comment]
With the above observation, I somehow managed to add ECDSA support to neverbleed.
I used openssl master branch.  Still there is debugging output everywhere, so after some cleanup, I will push my branch to github.

**Comment by kazuho** [comment]
Great!  I am looking forward to seeing it.

**Comment by tatsuhiro-t** [comment]
See my PR #11
All ECDSA related functions are prefixed with `ecdsa_` (one exception though, daemon_{get,set}_ecdsa}).  Probably, we should rename all RSA related ones to similar way, but I did not do that.

**Comment by tatsuhiro-t** [comment]
Now it compiles with OpenSSL 1.1.0pre5.
